<?php
$GLOBALS['textos']['idiomaAudio']='音声言語';
$GLOBALS['textos']['cualquiera']='任意の';
$GLOBALS['textos']['arrastrar']='オーディオ用のカテゴリを選択';
$GLOBALS['textos']['subir']='アップロード';
$GLOBALS['textos']['marcar']='場所のブランド';
$GLOBALS['textos']['errorSubida']='オーディオをアップロードしようとしたときにエラーが発生しました。';
$GLOBALS['textos']['audioMax']='最大ファイルサイズは2メガバイトオーディオですが、あなたのファイルは、{size}占める。';
$GLOBALS['textos']['noAudio']='あなたは、音声ファイルをアップロードする必要があります。';
$GLOBALS['textos']['correcto']='あなたのオーディオ正常にアップロードされています。';
$GLOBALS['textos']['descripcion']='説明';
$GLOBALS['textos']['describe']='あなたのオーディオのために簡単な説明を入力します';
$GLOBALS['textos']['direccion']='アドレス';
$GLOBALS['textos']['buscar']='検索';
$GLOBALS['textos']['aplicar']='適用する';
$GLOBALS['textos']['prefCat']='フィルタカテゴリ';
$GLOBALS['textos']['listaRepro']='プレイリスト';
$GLOBALS['textos']['info'][]=array('cabecera' => 'サービス', 'texto' => 'ビジネスについてのすべて。');
$GLOBALS['textos']['info'][]=array('cabecera' => '健康とウェルネス', 'texto' => '形で滞在するのに最適な場所を見つける。');
$GLOBALS['textos']['info'][]=array('cabecera' => 'ショッピング', 'texto' => '最高のお得な情報を探す。');
$GLOBALS['textos']['info'][]=array('cabecera' => 'レジャー', 'texto' => 'どこでもユニークな経験。');
$GLOBALS['textos']['info'][]=array('cabecera' => 'レストラン', 'texto' => '私はあなたをお勧め最高の料理に魅了される。');
$GLOBALS['textos']['info'][]=array('cabecera' => '活動', 'texto' => '自宅に滞在しないで、何かが常にある。');
$GLOBALS['textos']['info'][]=array('cabecera' => '宿泊施設', 'texto' => '家の近くや遠くの経験を見つけるためにコーナー。');
$GLOBALS['textos']['info'][]=array('cabecera' => '輸送', 'texto' => 'あなたが移動するために必要なすべてを見つける。');
$GLOBALS['textos']['info'][]=array('cabecera' => '<img src="http://panoraudio.com/img/new.png" alt="new"/>ものを見るために', 'texto' => '世界のいずれかを逃すと最高の提案を承っておりません。');
$GLOBALS['textos']['info'][]=array('cabecera' => '文化', 'texto' => '読み込みすることなく学ぶ。');
$GLOBALS['textos']['archivoAudio']='オーディオファイルを選択してください：';
$GLOBALS['textos']['archivoAudioMax']='最大2メガバイト';
$GLOBALS['textos']['rutas']='ルート';
$GLOBALS['textos']['registrar']='登録';
$GLOBALS['textos']['acceder']='ログイン';
$GLOBALS['textos']['dire']='アドレス';
$GLOBALS['textos']['marca']='説明';
$GLOBALS['textos']['fondoMarca']='あなたはブランドの写真を選択することができます。';
$GLOBALS['textos']['localizarse']='あなたが地図上に表示';
$GLOBALS['textos']['vistaLista']='リストビュー';
$GLOBALS['textos']['vistaMapa']='地図を表示する';
$GLOBALS['textos']['intercambiar']='写真と型カテゴリの切り替え';
$GLOBALS['textos']['seguiendo_titulo']='誰かがPanoraudioであなたに従います。';
$GLOBALS['textos']['meGusta_titulo']='誰かがあなたのオーディオの1が好き。';
$GLOBALS['textos']['nuevoAudio_titulo']='ユーザーPanoraudio新しいオーディオを作成しました。';