<?php
$GLOBALS['textos']['idiomaAudio']='Audio Language';
$GLOBALS['textos']['cualquiera']='Any';
$GLOBALS['textos']['arrastrar']='Select the category for the audio';
$GLOBALS['textos']['subir']='Upload';
$GLOBALS['textos']['marcar']='Place brand';
$GLOBALS['textos']['errorSubida']='An error occurred while trying to upload the audio';
$GLOBALS['textos']['audioMax']='The maximum size of the audio file is 2MB, your file occupies{size}.';
$GLOBALS['textos']['noAudio']='You must upload an audio file';
$GLOBALS['textos']['correcto']='Your audio is added correctly';
$GLOBALS['textos']['descripcion']='Description';
$GLOBALS['textos']['describe']='Enter a brief description for your audio';
$GLOBALS['textos']['direccion']='Address';
$GLOBALS['textos']['buscar']='search';
$GLOBALS['textos']['aplicar']='Apply';
$GLOBALS['textos']['prefCat']='Filter categories';
$GLOBALS['textos']['listaRepro']='Playlist';
$GLOBALS['textos']['info'][]=array('cabecera' => 'Services', 'texto' => 'Everything about Business.');
$GLOBALS['textos']['info'][]=array('cabecera' => 'Health and Wellness', 'texto' => 'Find the best places to stay in shape.');
$GLOBALS['textos']['info'][]=array('cabecera' => 'Shopping', 'texto' => 'Find the best deals.');
$GLOBALS['textos']['info'][]=array('cabecera' => 'Leisure', 'texto' => 'Unique experiences anywhere.');
$GLOBALS['textos']['info'][]=array('cabecera' => 'Restaurants', 'texto' => 'Be captivated by the best dishes that you recommend.');
$GLOBALS['textos']['info'][]=array('cabecera' => 'Activities', 'texto' => 'Do not stay at home, there is always something to do.');
$GLOBALS['textos']['info'][]=array('cabecera' => 'Accommodation', 'texto' => 'Places to find experiences near or far from home.');
$GLOBALS['textos']['info'][]=array('cabecera' => 'Transportation', 'texto' => 'Find everything you need to move.');
$GLOBALS['textos']['info'][]=array('cabecera' => '<img src="http://panoraudio.com/img/new.png" alt="new"/>What to see', 'texto' => 'Do not miss it for the world and listen to the best proposals.');
$GLOBALS['textos']['info'][]=array('cabecera' => 'Culture', 'texto' => 'Learn without reading.');
$GLOBALS['textos']['archivoAudio']='Choose the audio file:';
$GLOBALS['textos']['archivoAudioMax']='Maximum 2MB';
$GLOBALS['textos']['rutas']='Routes';
$GLOBALS['textos']['registrar']='Register';
$GLOBALS['textos']['acceder']='Log in';
$GLOBALS['textos']['dire']='Address';
$GLOBALS['textos']['marca']='Description';
$GLOBALS['textos']['fondoMarca']='You can choose a Photography for your brand:';
$GLOBALS['textos']['localizarse']='Locates you on the map';
$GLOBALS['textos']['vistaLista']='List';
$GLOBALS['textos']['vistaMapa']='Map';
$GLOBALS['textos']['intercambiar']='Switching between photo and type category';
$GLOBALS['textos']['seguiendo_titulo']='Someone follows you in Panoraudio.';
$GLOBALS['textos']['meGusta_titulo']='Someone likes one of your audios.';
$GLOBALS['textos']['nuevoAudio_titulo']='Panoraudio a user you have created a new audio.';