<?php
$GLOBALS['textos']['idiomaAudio']='Lingua audio';
$GLOBALS['textos']['cualquiera']='Qualsiasi';
$GLOBALS['textos']['arrastrar']="Selezionare la categoria per l'audio";
$GLOBALS['textos']['subir']='Caricare';
$GLOBALS['textos']['marcar']='Luogo del marchio';
$GLOBALS['textos']['errorSubida']="È verificato un errore durante il tentativo di caricare l'audio";
$GLOBALS['textos']['audioMax']='La dimensione massima del file audio è di 2MB, il file occupa{size}.';
$GLOBALS['textos']['noAudio']='È necessario caricare un file audio';
$GLOBALS['textos']['correcto']="L'audio viene aggiunto correttamente";
$GLOBALS['textos']['descripcion']='Descrizione';
$GLOBALS['textos']['describe']="Inserire una breve descrizione per l'audio";
$GLOBALS['textos']['direccion']='Indirizzo';
$GLOBALS['textos']['buscar']='Cerca';
$GLOBALS['textos']['aplicar']='Applicare';
$GLOBALS['textos']['prefCat']='Categorie Filtro';
$GLOBALS['textos']['listaRepro']='Lista di brani';
$GLOBALS['textos']['info'][]=array('cabecera' => 'Servizi', 'texto' => 'Tutto sugli affari.');
$GLOBALS['textos']['info'][]=array('cabecera' => 'Salute e Benessere', 'texto' => 'trova i migliori posti in cui stare in forma.');
$GLOBALS['textos']['info'][]=array('cabecera' => 'Shopping', 'texto' => 'Trova le migliori offerte.');
$GLOBALS['textos']['info'][]=array('cabecera' => 'Tempo libero', 'texto' => 'Esperienze uniche da nessuna parte.');
$GLOBALS['textos']['info'][]=array('cabecera' => 'Ristoranti', 'texto' => 'Lasciati coinvolgere dai migliori piatti che si consiglia.');
$GLOBALS['textos']['info'][]=array('cabecera' => 'Attività', 'texto' => 'Non stare a casa, c\'è sempre qualcosa da fare.');
$GLOBALS['textos']['info'][]=array('cabecera' => 'Alloggio', 'texto' => 'Luoghi per trovare le esperienze vicino o lontano da casa.');
$GLOBALS['textos']['info'][]=array('cabecera' => 'Trasporti', 'texto' => 'Trova tutto ciò che serve per muoversi.');
$GLOBALS['textos']['info'][]=array('cabecera' => '<img src="http://panoraudio.com/img/new.png" alt="new"/>Cosa vedere', 'texto' => 'Da non perdere per il mondo e ascoltare le proposte migliori.');
$GLOBALS['textos']['info'][]=array('cabecera' => 'Cultura', 'texto' => 'Imparare senza leggere.');
$GLOBALS['textos']['archivoAudio']='Scegliere il file audio:';
$GLOBALS['textos']['archivoAudioMax']='Massimo 2MB';
$GLOBALS['textos']['rutas']='Rotte';
$GLOBALS['textos']['registrar']='Registro';
$GLOBALS['textos']['acceder']='Log in';
$GLOBALS['textos']['dire']='Indirizzo';
$GLOBALS['textos']['marca']='Descrizione';
$GLOBALS['textos']['fondoMarca']='È possibile scegliere una foto per il marchio:';
$GLOBALS['textos']['localizarse']='Localizza la mappa che si';
$GLOBALS['textos']['vistaLista']='Visualizza la lista';
$GLOBALS['textos']['vistaMapa']='Visualizza la mappa';
$GLOBALS['textos']['intercambiar']='La commutazione tra foto e tipo di categoria';
$GLOBALS['textos']['seguiendo_titulo']='Quelqu\'un vous suit dans Panoraudio.';
$GLOBALS['textos']['meGusta_titulo']='A qualcuno piace uno dei tuoi audio.';
$GLOBALS['textos']['nuevoAudio_titulo']='Panoraudio un utente è stato creato un nuovo audio.';