<?php
$GLOBALS['textos']['idiomaAudio']='Audio eta hizkuntza';
$GLOBALS['textos']['cualquiera']='edozein';
$GLOBALS['textos']['arrastrar']='Hautatu kategoria audioa';
$GLOBALS['textos']['subir']='Igo';
$GLOBALS['textos']['marcar']='Tokia marka';
$GLOBALS['textos']['errorSubida']='Errore bat gertatu da audio igo';
$GLOBALS['textos']['audioMax']='Audio fitxategiaren gehienezko tamaina da 2MB, zure koadernoan okupatzen{size}.';
$GLOBALS['textos']['noAudio']='Audio fitxategi bat igo behar duzu';
$GLOBALS['textos']['correcto']='Zure audio da gehitu behar bezala';
$GLOBALS['textos']['descripcion']='Description';
$GLOBALS['textos']['describe']='Idatzi azalpen labur bat zure audio';
$GLOBALS['textos']['direccion']='helbidea';
$GLOBALS['textos']['buscar']='Bilatu';
$GLOBALS['textos']['aplicar']='Aplikatu';
$GLOBALS['textos']['prefCat']='Filter kategoria';
$GLOBALS['textos']['listaRepro']='Erreprodukzio zerrenda';
$GLOBALS['textos']['info'][]=array('cabecera' => 'Zerbitzuak', 'texto' => 'Business buruzko guztia.');
$GLOBALS['textos']['info'][]=array('cabecera' => 'Osasun eta Wellness', 'texto' => 'Aurkitu forma mantenduko lekuak.');
$GLOBALS['textos']['info'][]=array('cabecera' => 'Erosketak', 'texto' => 'best deals.');
$GLOBALS['textos']['info'][]=array('cabecera' => 'Aisia', 'texto' => 'berezia esperientziak edozein lekutan.');
$GLOBALS['textos']['info'][]=array('cabecera' => 'Jatetxeak', 'texto' => 'Be Gomendatzen plater onenak liluratuta.');
$GLOBALS['textos']['info'][]=array('cabecera' => 'Jarduerak', 'texto' => 'ez etxean, ez dago beti zerbait egin.');
$GLOBALS['textos']['info'][]=array('cabecera' => 'Ostatua', 'texto' => 'leku gertu edo urrun from home esperientziak aurkitu.');
$GLOBALS['textos']['info'][]=array('cabecera' => 'Garraioa', 'texto' => 'Aurkitu mugitu behar duzun guztia.');
$GLOBALS['textos']['info'][]=array('cabecera' => '<img src="http://panoraudio.com/img/new.png" alt="new"/>Zer ikusi', 'texto' => 'Ez galdu munduko eta proposamenak onena entzun.');
$GLOBALS['textos']['info'][]=array('cabecera' => 'Kultura', 'texto' => 'irakurketa gabe ikasi.');
$GLOBALS['textos']['archivoAudio']='Aukeratu audio-fitxategia:';
$GLOBALS['textos']['archivoAudioMax']='Gehienezko 2MB';
$GLOBALS['textos']['rutas']='Ibilbideak';
$GLOBALS['textos']['registrar']='Izena eman';
$GLOBALS['textos']['acceder']='saioa hasi';
$GLOBALS['textos']['dire']='helbidea';
$GLOBALS['textos']['marca']='marka';
$GLOBALS['textos']['fondoMarca']='Zure marka atzeko bat aukeratu ahal izango duzu:';
$GLOBALS['textos']['localizarse']='Aurkitu mapan duzu';
$GLOBALS['textos']['vistaLista']='Zerrendaren ikuspegia';
$GLOBALS['textos']['vistaMapa']='Mapan ikusi';
$GLOBALS['textos']['intercambiar']='Argazki eta mota kategoria batetik bestera aldatzea';