<?php
$GLOBALS['textos']['idiomaAudio']='Langue audio';
$GLOBALS['textos']['cualquiera']='Tout';
$GLOBALS['textos']['arrastrar']="Sélectionnez la catégorie pour l'audio";
$GLOBALS['textos']['subir']='Téléchargez';
$GLOBALS['textos']['marcar']='Lieu de marque';
$GLOBALS['textos']['errorSubida']="Une erreur s'est produite tout en essayant de télécharger l'audio";
$GLOBALS['textos']['audioMax']="La taille maximale du fichier audio est de 2 Mo, le fichier occupe{size}.";
$GLOBALS['textos']['noAudio']='Vous devez télécharger un fichier audio';
$GLOBALS['textos']['correcto']='Votre audio est correctement ajouté';
$GLOBALS['textos']['descripcion']='Description';
$GLOBALS['textos']['describe']='Entrez une brève description de vos fichiers audio';
$GLOBALS['textos']['direccion']='Adresse';
$GLOBALS['textos']['buscar']='Rechercher';
$GLOBALS['textos']['aplicar']='Appliquer';
$GLOBALS['textos']['prefCat']='Filtre catégories';
$GLOBALS['textos']['listaRepro']='Playlist';
$GLOBALS['textos']['info'][]=array('cabecera' => 'Services', 'texto' => 'Tout sur les entreprises.');
$GLOBALS['textos']['info'][]=array('cabecera' => 'Santé et bien-être', 'texto' => 'Trouvez les meilleurs endroits pour rester en forme.');
$GLOBALS['textos']['info'][]=array('cabecera' => 'Shopping', 'texto' => 'Trouvez les meilleures offres.');
$GLOBALS['textos']['info'][]=array('cabecera' => 'Loisirs', 'texto' => 'expériences uniques partout.');
$GLOBALS['textos']['info'][]=array('cabecera' => 'Restaurants', 'texto' => 'Laissez-vous séduire par les meilleurs plats que vous recommandez.');
$GLOBALS['textos']['info'][]=array('cabecera' => 'Activités', 'texto' => 'Ne restez pas à la maison, il ya toujours quelque chose à faire.');
$GLOBALS['textos']['info'][]=array('cabecera' => 'Hébergement', 'texto' => 'endroits pour trouver des expériences proches ou loin de chez eux.');
$GLOBALS['textos']['info'][]=array('cabecera' => 'Transport', 'texto' => 'Trouvez tout ce dont vous avez besoin pour passer.');
$GLOBALS['textos']['info'][]=array('cabecera' => '<img src="http://panoraudio.com/img/new.png" alt="new"/>A voir', 'texto' => 'A ne pas manquer pour le monde et écouter les meilleures propositions.');
$GLOBALS['textos']['info'][]=array('cabecera' => 'Culture', 'texto' => 'Apprendre sans lecture.');
$GLOBALS['textos']['archivoAudio']='Choisissez le fichier audio:';
$GLOBALS['textos']['archivoAudioMax']='2MB maximum';
$GLOBALS['textos']['rutas']='Routes';
$GLOBALS['textos']['registrar']='Enregistrer';
$GLOBALS['textos']['acceder']='Connexion';
$GLOBALS['textos']['dire']='Adresse';
$GLOBALS['textos']['marca']='Description';
$GLOBALS['textos']['fondoMarca']='Vous pouvez choisir une photo pour la marque:';
$GLOBALS['textos']['localizarse']='Localiser sur la carte que vous';
$GLOBALS['textos']['vistaLista']='Liste';
$GLOBALS['textos']['vistaMapa']='Carte';
$GLOBALS['textos']['intercambiar']='La commutation entre photo et le type catégorie';
$GLOBALS['textos']['seguiendo_titulo']='Quelqu\'un vous suit dans Panoraudio.';
$GLOBALS['textos']['meGusta_titulo']='Quelqu\'un aime un de vos audios.';
$GLOBALS['textos']['nuevoAudio_titulo']='Panoraudio un utilisateur que vous avez créé une nouvelle audio.';