<?php
$GLOBALS['textos']['idiomaAudio']='Idioma del audio';
$GLOBALS['textos']['cualquiera']='Cualquiera';
$GLOBALS['textos']['arrastrar']='Selecciona la categoría para el audio';
$GLOBALS['textos']['subir']='Subir';
$GLOBALS['textos']['marcar']='Situar marca';
$GLOBALS['textos']['errorSubida']='Se produjo un error al intentar subir el audio.';
$GLOBALS['textos']['audioMax']='El tamaño máximo del archivo de audio es de 2MB, tu archivo ocupa {size}.';
$GLOBALS['textos']['noAudio']='Debes subir un archivo de audio.';
$GLOBALS['textos']['correcto']='Tu audio se ha subido correctamente.';
$GLOBALS['textos']['descripcion']='Descripción';
$GLOBALS['textos']['describe']='Introduce una breve descripción para tu audio';
$GLOBALS['textos']['direccion']='Dirección o descripción de marca';
$GLOBALS['textos']['buscar']='Buscar';
$GLOBALS['textos']['aplicar']='Aplicar';
$GLOBALS['textos']['prefCat']='Filtro de categorías';
$GLOBALS['textos']['listaRepro']='Lista de reproducción';
$GLOBALS['textos']['info'][]=array('cabecera' => 'Servicios', 'texto' => 'Todo lo relacionado con Empresas.');
$GLOBALS['textos']['info'][]=array('cabecera' => 'Salud y Bienestar', 'texto' => 'Encuentra los mejores sitios para estar en forma.');
$GLOBALS['textos']['info'][]=array('cabecera' => 'Shopping', 'texto' => 'Encuentra las mejores ofertas.');
$GLOBALS['textos']['info'][]=array('cabecera' => 'Ocio', 'texto' => 'Experiencias únicas en cualquier lugar.');
$GLOBALS['textos']['info'][]=array('cabecera' => 'Restaurantes', 'texto' => 'Déjate seducir por los mejores platos que te recomiendan.');
$GLOBALS['textos']['info'][]=array('cabecera' => 'Actividades', 'texto' => 'No te quedes en casa,hay siempre algo que hacer.');
$GLOBALS['textos']['info'][]=array('cabecera' => 'Alojamiento', 'texto' => 'Rincones para encontrar experiencias cerca o lejos de casa.');
$GLOBALS['textos']['info'][]=array('cabecera' => 'Transporte', 'texto' => 'Encuentra todo lo que necesitas para desplazarte.');
$GLOBALS['textos']['info'][]=array('cabecera' => '<img src="http://panoraudio.com/img/new.png" alt="new"/>Que Ver', 'texto' => 'No te pierdas nada del Mundo y escucha las mejores propuestas.');
$GLOBALS['textos']['info'][]=array('cabecera' => 'Cultura', 'texto' => 'Aprende sin tener que leer.');
$GLOBALS['textos']['archivoAudio']='Elige el archivo de audio:';
$GLOBALS['textos']['archivoAudioMax']='Máximo 4MB';
$GLOBALS['textos']['rutas']='Rutas';
$GLOBALS['textos']['registrar']='REGISTRARME';
$GLOBALS['textos']['acceder']='Acceder';
$GLOBALS['textos']['dire']='Dirección';
$GLOBALS['textos']['marca']='Descripción';
$GLOBALS['textos']['fondoMarca']='Puedes seleccionar una Fotografía para tu marca:';
$GLOBALS['textos']['localizarse']='Localízate en el mapa';
$GLOBALS['textos']['vistaLista']='Lista';
$GLOBALS['textos']['vistaMapa']='Mapa';
$GLOBALS['textos']['intercambiar']='Intercambiar entre foto y tipo categoría';