<?php
$GLOBALS['textos']['idiomaAudio']='音頻語言';
$GLOBALS['textos']['cualquiera']='任何';
$GLOBALS['textos']['arrastrar']='選擇一個類別音頻';
$GLOBALS['textos']['subir']='上載';
$GLOBALS['textos']['marcar']='Place品牌';
$GLOBALS['textos']['errorSubida']='有一個錯誤，當試圖上載音頻。';
$GLOBALS['textos']['audioMax']='最大文件大小為2MB音頻，文件佔用{size}。';
$GLOBALS['textos']['noAudio']='你要上傳的音頻文件。';
$GLOBALS['textos']['correcto']='已經成功上傳你的音頻。';
$GLOBALS['textos']['descripcion']='描述';
$GLOBALS['textos']['describe']='為您的音頻，輸入一個簡短的描述';
$GLOBALS['textos']['direccion']='地址';
$GLOBALS['textos']['buscar']='搜索';
$GLOBALS['textos']['aplicar']='申請';
$GLOBALS['textos']['prefCat']='過濾類別';
$GLOBALS['textos']['listaRepro']='播放列表';
$GLOBALS['textos']['info'][]=array('cabecera' => '服務', 'texto' => '一切有關業務。');
$GLOBALS['textos']['info'][]=array('cabecera' => '衛生與健康', 'texto' => '尋找最好的地方，保持體形。');
$GLOBALS['textos']['info'][]=array('cabecera' => '購物', 'texto' => '尋找最好的交易。');
$GLOBALS['textos']['info'][]=array('cabecera' => '閒暇', 'texto' => '獨特的經驗，在任何地方。');
$GLOBALS['textos']['info'][]=array('cabecera' => '餐館', 'texto' => '被誘惑的，我建議你最好的菜。');
$GLOBALS['textos']['info'][]=array('cabecera' => '活動', 'texto' => '不要呆在家裡，總是有事可做。');
$GLOBALS['textos']['info'][]=array('cabecera' => '住宿', 'texto' => '角落找到接近或遠離家鄉的經驗。');
$GLOBALS['textos']['info'][]=array('cabecera' => '運輸', 'texto' => '找到所有你需要移動');
$GLOBALS['textos']['info'][]=array('cabecera' => '<img src="http://panoraudio.com/img/new.png" alt="new"/>看到什麼', 'texto' => '不要錯過任何的世界，聽到的最好的建議。');
$GLOBALS['textos']['info'][]=array('cabecera' => '文化', 'texto' => '學習，而不必閱讀。');
$GLOBALS['textos']['archivoAudio']='選擇音頻文件：';
$GLOBALS['textos']['archivoAudioMax']='最大2MB';
$GLOBALS['textos']['rutas']='路線';
$GLOBALS['textos']['registrar']='註冊';
$GLOBALS['textos']['acceder']='登錄';
$GLOBALS['textos']['dire']='地址';
$GLOBALS['textos']['marca']='描述';
$GLOBALS['textos']['fondoMarca']='您可以选择的品牌照片：';
$GLOBALS['textos']['localizarse']='在地圖上定位你';
$GLOBALS['textos']['vistaLista']='列表視圖';
$GLOBALS['textos']['vistaMapa']='查看地圖';
$GLOBALS['textos']['intercambiar']='照片和類型類別之間切換';