<?php
$GLOBALS['textos']['idiomaAudio']='Audio Sprache';
$GLOBALS['textos']['cualquiera']='Jeder';
$GLOBALS['textos']['arrastrar']='Wählen Sie eine Kategorie für die Audio';
$GLOBALS['textos']['subir']='Laden';
$GLOBALS['textos']['marcar']='Markieren';
$GLOBALS['textos']['errorSubida']='Ein Fehler ist aufgetreten beim Versuch, die audio upload';
$GLOBALS['textos']['audioMax']='Die maximale Größe der Audio-Datei ist 2MB, nimmt Ihre Datei{size}.';
$GLOBALS['textos']['noAudio']='Sie müssen laden Sie eine Audio-Datei';
$GLOBALS['textos']['correcto']='Ihr Ton wird korrekt hinzugefügt';
$GLOBALS['textos']['descripcion']='Beschreibung';
$GLOBALS['textos']['describe']='Geben Sie eine kurze Beschreibung für Ihre Audio';
$GLOBALS['textos']['direccion']='Adresse';
$GLOBALS['textos']['buscar']='Suchen';
$GLOBALS['textos']['aplicar']='Anwenden';
$GLOBALS['textos']['prefCat']='Filter-Kategorien';
$GLOBALS['textos']['listaRepro']='Playliste';
$GLOBALS['textos']['info'][]=array('cabecera' => 'Services', 'texto' => 'Alles über Business.');
$GLOBALS['textos']['info'][]=array('cabecera' => 'Gesundheit und Wellness', 'texto' => 'Hier finden Sie die besten Orte, um in Form zu bleiben.');
$GLOBALS['textos']['info'][]=array('cabecera' => 'Shopping', 'texto' => 'Finden Sie die besten Angebote.');
$GLOBALS['textos']['info'][]=array('cabecera' => 'Freizeit', 'texto' => 'Einzigartige Erlebnisse überall.');
$GLOBALS['textos']['info'][]=array('cabecera' => 'Restaurants', 'texto' => 'Von den besten Gerichte, die Sie empfehlen fesseln.');
$GLOBALS['textos']['info'][]=array('cabecera' => 'Aktivitäten', 'texto' => 'Nicht zu Hause bleiben, es gibt immer etwas zu tun.');
$GLOBALS['textos']['info'][]=array('cabecera' => 'Unterkunft', 'texto' => 'Plätze Erfahrungen nah oder fern von zu Hause zu finden.');
$GLOBALS['textos']['info'][]=array('cabecera' => 'Transport', 'texto' => 'Finden Sie alles, was Sie brauchen, um zu bewegen.');
$GLOBALS['textos']['info'][]=array('cabecera' => '<img src="http://panoraudio.com/img/new.png" alt="new"/>Was zu sehen', 'texto' => 'Verpassen Sie es nicht für die Welt und lauschen Sie den besten Vorschläge.');
$GLOBALS['textos']['info'][]=array('cabecera' => 'Kultur', 'texto' => 'Lernen ohne zu lesen.');
$GLOBALS['textos']['archivoAudio']='Wählen Sie die Audio-Datei:';
$GLOBALS['textos']['archivoAudioMax']='Maximale 2MB';
$GLOBALS['textos']['rutas']='Routen';
$GLOBALS['textos']['registrar']='Registrieren';
$GLOBALS['textos']['acceder']='Einloggen';
$GLOBALS['textos']['dire']='Adresse';
$GLOBALS['textos']['marca']='Beschreibung';
$GLOBALS['textos']['fondoMarca']='Sie können ein Bild für Ihre Marke wählen:';
$GLOBALS['textos']['localizarse']='Sie sucht auf der Karte';
$GLOBALS['textos']['vistaLista']='Listenansicht';
$GLOBALS['textos']['vistaMapa']='Karte anzeigen';
$GLOBALS['textos']['intercambiar']='Das Umschalten zwischen Foto und Typ Kategorie';