<?php
$GLOBALS['textos']['idiomaAudio']='Idioma de Audio';
$GLOBALS['textos']['cualquiera']='Calquera';
$GLOBALS['textos']['arrastrar']='Seleccione a categoría para o audio';
$GLOBALS['textos']['subir']='Cargar';
$GLOBALS['textos']['marcar']='Situar marca';
$GLOBALS['textos']['errorSubida']='Houbo un erro ao tentar cargar o audio';
$GLOBALS['textos']['audioMax']='O tamaño máximo do ficheiro de audio é de 2MB, o arquivo ocupa{size}.';
$GLOBALS['textos']['noAudio']='Debe subir un arquivo de audio';
$GLOBALS['textos']['correcto']='O seu audio é engadido correctamente';
$GLOBALS['textos']['descripcion']='Descrición';
$GLOBALS['textos']['describe']='Escriba unha breve descrición para o seu audio';
$GLOBALS['textos']['direccion']='Enderezo';
$GLOBALS['textos']['buscar']='Procurar';
$GLOBALS['textos']['aplicar']='Aplicar';
$GLOBALS['textos']['prefCat']='Filtro de categorías';
$GLOBALS['textos']['listaRepro']='Lista de reproducción';
$GLOBALS['textos']['info'][]=array('cabecera' => 'Servizos', 'texto' => 'Todo o relacionado con Empresas.');
$GLOBALS['textos']['info'][]=array('cabecera' => 'Saúde', 'texto' => 'Encontra os mellores sitios para estar en forma.');
$GLOBALS['textos']['info'][]=array('cabecera' => 'Shopping', 'texto' => ' Encontra as mellores ofertas.');
$GLOBALS['textos']['info'][]=array('cabecera' => 'Ocio', 'texto' => 'Experiencias unicas en calquera lugar.');
$GLOBALS['textos']['info'][]=array('cabecera' => 'Restaurantes', 'texto' => 'Dejate seducir polos mellores pratos que che recomendan.');
$GLOBALS['textos']['info'][]=array('cabecera' => 'Actividades', 'texto' => 'Non quedes na casa, hay sempre algo que facer.');
$GLOBALS['textos']['info'][]=array('cabecera' => 'Aloxamento', 'texto' => 'Lugares para encontrar experiencias preto ou lonxe da casa.');
$GLOBALS['textos']['info'][]=array('cabecera' => 'Transporte', 'texto' => 'Encontra todo o que necesitas para desprazarte.');
$GLOBALS['textos']['info'][]=array('cabecera' => '<img src="http://panoraudio.com/img/new.png" alt="new"/>Que Ver', 'texto' => 'Non che perdas nada do Mundo e escoita as mellores propostas.');
$GLOBALS['textos']['info'][]=array('cabecera' => 'Cultura', 'texto' => 'Aprende sen ter que ler.');
$GLOBALS['textos']['archivoAudio']='Escolla o ficheiro de son:';
$GLOBALS['textos']['archivoAudioMax']='Máximo 2MB';
$GLOBALS['textos']['rutas']='Rutas';
$GLOBALS['textos']['registrar']='Rexistrarse';
$GLOBALS['textos']['acceder']='Acceso';
$GLOBALS['textos']['dire']='Enderezo';
$GLOBALS['textos']['marca']='Descrición';
$GLOBALS['textos']['fondoMarca']='Pode escoller una fotografía para a súa marca:';
$GLOBALS['textos']['localizarse']='Localízate no mapa';
$GLOBALS['textos']['vistaLista']='Lista';
$GLOBALS['textos']['vistaMapa']='Mapa';
$GLOBALS['textos']['intercambiar']='Alternando entre fotografía e tipo de categoría';
$GLOBALS['textos']['seguiendo_titulo']='Alguén séguete en Panoraudio.';
$GLOBALS['textos']['meGusta_titulo']='Alguén lle gusta un dos teus audios.';
$GLOBALS['textos']['nuevoAudio_titulo']='Un usuario de Panoraudio creou un novo son.';