<?php
$GLOBALS['textos']['registro_titulo']="Registra't";
$GLOBALS['textos']['email']='Email';
$GLOBALS['textos']['usuario']='Usuari';
$GLOBALS['textos']['emailUsuario']='Email o usuari';
$GLOBALS['textos']['pass']='Contrasenya';
$GLOBALS['textos']['pass2']='Repeteix la contrasenya';
$GLOBALS['textos']['login_titulo']='Accedeix';
$GLOBALS['textos']['registrar']='Registrar';
$GLOBALS['textos']['entrar']='Entrada';
$GLOBALS['textos']['recordar']='Recordar accés';
$GLOBALS['textos']['acuerdo']='Acord de llicència';
$GLOBALS['textos']['mensaje_registrado']="T'has registrat correctament. Ara revisa el teu email per acabar el procés.Potser troba estat emmagatzemat com SPAM.";
$GLOBALS['textos']['manual']='';
$GLOBALS['textos']['contacta']='Contacta';
$GLOBALS['textos']['mensaje_activado']='El teu compte ha estat activat. Ara prova a accedir.';
$GLOBALS['textos']['recuperar']='Recuperar contrasenya';
$GLOBALS['textos']['recuperarEmail']='Procés completat. Revisa el teu email per obtenir més instruccions.';
$GLOBALS['textos']['cambiadoPass']='La contrasenya s\'ha modificat amb èxit.';