<?php
$GLOBALS['textos']['idiomaAudio']="Idioma de l'audio";
$GLOBALS['textos']['cualquiera']='Qualsevol';
$GLOBALS['textos']['arrastrar']="Selecciona la categoria per l'audio";
$GLOBALS['textos']['subir']='Pujar';
$GLOBALS['textos']['marcar']='Situar marca';
$GLOBALS['textos']['errorSubida']="S'ha product un error en intentar pujar l'audio";
$GLOBALS['textos']['audioMax']="La mida máxim de l'arxiu d'audio es de 2MB, el teu arxiu ocupa{size}.";
$GLOBALS['textos']['noAudio']="Has pujar un arxiu d'audio";
$GLOBALS['textos']['correcto']="El teu audio s'ha pujat correctament";
$GLOBALS['textos']['descripcion']="Descripción";
$GLOBALS['textos']['describe']="Introdueix una breu descripció per al teu audio";
$GLOBALS['textos']['direccion']='Direcció';
$GLOBALS['textos']['buscar']='Cercar';
$GLOBALS['textos']['aplicar']='Aplicar';
$GLOBALS['textos']['prefCat']='Filtre de categories';
$GLOBALS['textos']['listaRepro']='Llista de reproducció';
$GLOBALS['textos']['info'][]=array('cabecera' => 'Serveis', 'texto' => 'Tot el relacionat amb Empreses.');
$GLOBALS['textos']['info'][]=array('cabecera' => 'Salut i Benestar', 'texto' => 'Troba els millors llocs per estar en forma.');
$GLOBALS['textos']['info'][]=array('cabecera' => 'Shopping', 'texto' => 'Troba les millors ofertes.');
$GLOBALS['textos']['info'][]=array('cabecera' => 'Oci', 'texto' => 'Experiències úniques en qualsevol lloc.');
$GLOBALS['textos']['info'][]=array('cabecera' => 'Restaurants', 'texto' => 'Deixa\'t seduir pels millors plats que et recomanen.');
$GLOBALS['textos']['info'][]=array('cabecera' => 'Activitats', 'texto' => 'No et quedis a casa, hi ha sempre alguna cosa a fer.');
$GLOBALS['textos']['info'][]=array('cabecera' => 'Allotjament', 'texto' => 'Racons per trobar experiències prop o lluny de casa.');
$GLOBALS['textos']['info'][]=array('cabecera' => 'Transport', 'texto' => 'Troba tot el que necessites per desplaçar.');
$GLOBALS['textos']['info'][]=array('cabecera' => '<img src="http://panoraudio.com/img/new.png" alt="new"/>Que Veure', 'texto' => 'No et perdis res del Món i escolta les millors propostes.');
$GLOBALS['textos']['info'][]=array('cabecera' => 'Cultura', 'texto' => 'Aprèn sense haver de llegir.');
$GLOBALS['textos']['archivoAudio']='Tria l\'arxiu d\'àudio:';
$GLOBALS['textos']['archivoAudioMax']='Màxim 2MB';
$GLOBALS['textos']['rutas']='Rutes';
$GLOBALS['textos']['registrar']='Registrar';
$GLOBALS['textos']['acceder']='Accedir';
$GLOBALS['textos']['dire']='Direcció';
$GLOBALS['textos']['marca']='Descripció';
$GLOBALS['textos']['fondoMarca']='Pots seleccionar una Fotografia per a la teva marca:';
$GLOBALS['textos']['localizarse']='Localitza et al mapa';
$GLOBALS['textos']['vistaLista']='Vista de llista';
$GLOBALS['textos']['vistaMapa']='Vista del mapa';
$GLOBALS['textos']['intercambiar']='Intercanviar entre foto i tipus categoria';