<?php
$GLOBALS['textos']['idiomaAudio']='Idioma de Áudio';
$GLOBALS['textos']['cualquiera']='Qualquier';
$GLOBALS['textos']['arrastrar']='Selecione uma categoria para áudio';
$GLOBALS['textos']['subir']='Carregar';
$GLOBALS['textos']['marcar']='Colocar marca';
$GLOBALS['textos']['errorSubida']='Ocorreu um erro ao tentar carregar o áudio.';
$GLOBALS['textos']['audioMax']='O tamanho máximo do arquivo de áudio é de 2MB, o arquivo ocupa {size}.';
$GLOBALS['textos']['noAudio']='Você deve fazer upload de um arquivo de áudio.';
$GLOBALS['textos']['correcto']='Seu áudio é adicionado corretamente.';
$GLOBALS['textos']['descripcion']='Descrição';
$GLOBALS['textos']['describe']='Digite uma breve descrição sobre o seu áudio';
$GLOBALS['textos']['direccion']='Endereço';
$GLOBALS['textos']['buscar']='Pesquisar';
$GLOBALS['textos']['aplicar']='Aplicar';
$GLOBALS['textos']['prefCat']='Filtro de categorias';
$GLOBALS['textos']['listaRepro']='Lista de reprodução';
$GLOBALS['textos']['info'][]=array('cabecera' => 'Serviços', 'texto' => 'Tudo sobre o negócio.');
$GLOBALS['textos']['info'][]=array('cabecera' => 'Saúde e Bem-Estar', 'texto' => 'Encontre os melhores lugares para ficar em forma.');
$GLOBALS['textos']['info'][]=array('cabecera' => 'Compras', 'texto' => 'Encontre as melhores ofertas.');
$GLOBALS['textos']['info'][]=array('cabecera' => 'Lazer', 'texto' => 'Experiências únicas em qualquer lugar.');
$GLOBALS['textos']['info'][]=array('cabecera' => 'Restaurantes', 'texto' => 'Deixe-se cativar pelos melhores pratos que você recomenda.');
$GLOBALS['textos']['info'][]=array('cabecera' => 'Atividades', 'texto' => 'Não ficar em casa, há sempre algo para fazer.');
$GLOBALS['textos']['info'][]=array('cabecera' => 'Alojamento', 'texto' => 'Lugares para encontrar experiências perto ou longe de casa.');
$GLOBALS['textos']['info'][]=array('cabecera' => 'Transportes', 'texto' => 'Encontre tudo que você precisa para se mover.');
$GLOBALS['textos']['info'][]=array('cabecera' => '<img src="http://panoraudio.com/img/new.png" alt="new"/>O que ver', 'texto' => 'Não perca para o mundo e ouvir as melhores propostas.');
$GLOBALS['textos']['info'][]=array('cabecera' => 'Cultura', 'texto' => 'Aprenda sem ler.');
$GLOBALS['textos']['archivoAudio']='Escolha o arquivo de áudio:';
$GLOBALS['textos']['archivoAudioMax']='Máximo 2MB';
$GLOBALS['textos']['rutas']='Rotas';
$GLOBALS['textos']['registrar']='Registrar';
$GLOBALS['textos']['acceder']='Entrar';
$GLOBALS['textos']['dire']='Endereço';
$GLOBALS['textos']['marca']='Descrição';
$GLOBALS['textos']['fondoMarca']='Você pode escolher uma foto para a marca:';
$GLOBALS['textos']['localizarse']='Localize no mapa você';
$GLOBALS['textos']['vistaLista']='Ver Lista';
$GLOBALS['textos']['vistaMapa']='Ver mapa';
$GLOBALS['textos']['intercambiar']='Alternando entre fotografia e tipo de categoria';
$GLOBALS['textos']['seguiendo_titulo']='Alguém te segue em Panoraudio.';
$GLOBALS['textos']['meGusta_titulo']='Alguém gosta de um de seus áudios.';
$GLOBALS['textos']['nuevoAudio_titulo']='Panoraudio um usuário de ter criado um novo áudio.';